# Generated by Django 6.0.3 on 2026-04-16 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ArtistContext',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_comment='コンテキスト名', max_length=64, verbose_name='コンテキスト名')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'アーティストコンテキストマスタ',
                'verbose_name_plural': 'アーティストコンテキストマスタ',
                'db_table': 'm_artist_context',
                'db_table_comment': 'アーティストコンテキストマスタ',
            },
        ),
        migrations.CreateModel(
            name='M_ArtistTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_comment='タグ名', max_length=64, verbose_name='タグ名')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'アーティストタグマスタ',
                'verbose_name_plural': 'アーティストタグマスタ',
                'db_table': 'm_artist_tag',
                'db_table_comment': 'アーティストタグマスタ',
            },
        ),
        migrations.CreateModel(
            name='R_ArtistTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('tag', models.ForeignKey(db_column='tag_id', db_comment='タグ', on_delete=django.db.models.deletion.CASCADE, related_name='tag_r_artist_tag_set', to='artist.m_artisttag', verbose_name='タグ')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'アーティストタグリレーション',
                'verbose_name_plural': 'アーティストタグリレーション',
                'db_table': 'r_artist_tag',
                'db_table_comment': 'アーティストタグリレーション',
            },
        ),
        migrations.CreateModel(
            name='T_Artist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(db_column='spotify_id', db_comment='Spotify/ID', max_length=255, verbose_name='Spotify/ID')),
                ('name', models.CharField(db_column='name', db_comment='アーティスト名', max_length=255, verbose_name='アーティスト名')),
                ('setlistfm_mbid', models.CharField(blank=True, db_column='setlistfm_mbid', db_comment='setlistfm_mbid', max_length=100, null=True, verbose_name='SetlistFm/MBID')),
                ('is_mbid_autoset', models.BooleanField(db_column='is_mbid_autoset', db_comment='MBID/自動紐付けフラグ', default=False, verbose_name='MBID/自動紐付けフラグ')),
                ('genres', models.JSONField(blank=True, db_column='genres', db_comment='ジャンル', default=list, verbose_name='ジャンル')),
                ('context', models.ForeignKey(blank=True, db_column='context', db_comment='コンテキスト', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_t_artist_set', to='artist.m_artistcontext', verbose_name='コンテキスト')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('spotify_image', models.ForeignKey(blank=True, db_column='spotify_image_id', db_comment='Spotify画像', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotify_image_t_artist_set', to='common.t_fileresource', verbose_name='Spotify画像')),
                ('tags', models.ManyToManyField(db_comment='タグ', related_name='tags_t_artist_set', through='artist.R_ArtistTag', to='artist.m_artisttag', verbose_name='タグ')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='ユーザ', on_delete=django.db.models.deletion.CASCADE, related_name='user_t_artist_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'アーティストトラン',
                'verbose_name_plural': 'アーティストトラン',
                'db_table': 't_artist',
                'db_table_comment': 'アーティストトラン',
            },
        ),
        migrations.AddField(
            model_name='r_artisttag',
            name='artist',
            field=models.ForeignKey(db_column='artist_id', db_comment='アーティスト', on_delete=django.db.models.deletion.CASCADE, related_name='artist_r_artist_tag_set', to='artist.t_artist', verbose_name='アーティスト'),
        ),
        migrations.AddConstraint(
            model_name='m_artistcontext',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_m_artist_context_name_active'),
        ),
        migrations.AddConstraint(
            model_name='m_artisttag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_m_artist_tag_name_active'),
        ),
        migrations.AddConstraint(
            model_name='t_artist',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'spotify_id'), name='unique_t_artist_user_sporify_id_active'),
        ),
        migrations.AddConstraint(
            model_name='r_artisttag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('artist', 'tag'), name='unique_r_artist_tag_artist_tag_active'),
        ),
    ]
