# Generated by Django 6.0.3 on 2026-04-12 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_artist',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_comment='ユーザ', on_delete=django.db.models.deletion.CASCADE, related_name='user_t_artist_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
    ]
