# Generated by Django 6.0.3 on 2026-04-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_artist',
            name='genres',
        ),
    ]
