# Generated by Django 6.0.3 on 2026-04-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_t_artist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_artist',
            name='lastfm_name',
            field=models.CharField(blank=True, db_column='lastfm_name', db_comment='アーティスト名/LastFM', max_length=255, null=True, verbose_name='アーティスト名/LastFM'),
        ),
    ]
