# Generated by Django 6.0.3 on 2026-04-22 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_t_artist_lastfm_name'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='t_artist',
            name='unique_t_artist_user_deezer_id_active',
        ),
        migrations.AddField(
            model_name='t_artist',
            name='is_deezer_autoset',
            field=models.BooleanField(db_column='is_deezer_autoset', db_comment='Deezer/自動紐付けフラグ', default=False, verbose_name='Deezer/自動紐付けフラグ'),
        ),
        migrations.AddField(
            model_name='t_artist',
            name='spotify_id',
            field=models.CharField(db_column='spotify_id', db_comment='Spotify/ID', default='', max_length=255, verbose_name='Spotify/ID'),
        ),
        migrations.AddField(
            model_name='t_artist',
            name='spotify_image',
            field=models.ForeignKey(blank=True, db_column='spotify_image_id', db_comment='Spotify画像', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotify_image_t_artist_set', to='common.t_fileresource', verbose_name='Spotify画像'),
        ),
        migrations.AlterField(
            model_name='t_artist',
            name='deezer_id',
            field=models.CharField(blank=True, db_column='deezer_id', db_comment='Deezer/ID', max_length=255, null=True, verbose_name='Deezer/ID'),
        ),
        migrations.AddConstraint(
            model_name='t_artist',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'spotify_id'), name='unique_t_artist_user_spotify_id_active'),
        ),
        migrations.RemoveField(
            model_name='t_artist',
            name='deezer_image',
        ),
    ]
