# Generated by Django 6.0.3 on 2026-04-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_remove_t_artist_unique_t_artist_user_deezer_id_active_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_artist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='t_artist',
            name='setlistfm_mbid',
        ),
        migrations.RemoveField(
            model_name='t_artist',
            name='spotify_image',
        ),
        migrations.AddField(
            model_name='t_artist',
            name='display_name',
            field=models.CharField(blank=True, db_column='display_name', db_comment='アーティスト表示名', max_length=255, null=True, verbose_name='アーティスト表示名'),
        ),
        migrations.AddField(
            model_name='t_artist',
            name='external_icon',
            field=models.ForeignKey(blank=True, db_column='external_icon_id', db_comment='外部アイコン', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_icon_t_artist_set', to='common.t_fileresource', verbose_name='外部アイコン'),
        ),
        migrations.AddField(
            model_name='t_artist',
            name='mbid',
            field=models.CharField(blank=True, db_column='mbid', db_comment='MBID', max_length=100, null=True, verbose_name='MBID'),
        ),
        migrations.AddField(
            model_name='t_artist',
            name='spotify_name',
            field=models.CharField(db_column='spotify_name', db_comment='Spotify/アーティスト名', default=1, max_length=255, verbose_name='Spotify/アーティスト名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_artist',
            name='sync_at',
            field=models.DateTimeField(blank=True, db_column='sync_at', db_comment='同期日時', null=True, verbose_name='同期日時'),
        ),
        migrations.AlterField(
            model_name='t_artist',
            name='lastfm_name',
            field=models.CharField(blank=True, db_column='lastfm_name', db_comment='LastFM/アーティスト名', max_length=255, null=True, verbose_name='LastFM/アーティスト名'),
        ),
        migrations.AlterField(
            model_name='t_artist',
            name='spotify_id',
            field=models.CharField(db_column='spotify_id', db_comment='Spotify/ID', max_length=255, verbose_name='Spotify/ID'),
        ),
    ]
