# Generated by Django 6.0.3 on 2026-04-08 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_SpotifyUserToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(db_column='access_token', db_comment='アクセストークン', verbose_name='アクセストークン')),
                ('refresh_token', models.TextField(db_column='refresh_token', db_comment='リフレッシュトークン', verbose_name='リフレッシュトークン')),
                ('expired_at', models.DateTimeField(db_column='expired_at', db_comment='トークン有効期限', verbose_name='トークン有効期限')),
                ('refreshing', models.BooleanField(db_column='refreshing', db_comment='リフレッシュロックフラグ', default=False, verbose_name='リフレッシュロックフラグ')),
                ('refreshing_until', models.DateTimeField(blank=True, db_column='refreshing_until', db_comment='リフレッシュ更新ロック期限', null=True, verbose_name='リフレッシュ更新ロック期限')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'Spotifyトークントラン',
                'verbose_name_plural': 'Spotifyトークントラン',
                'db_table': 't_spotify_token',
                'db_table_comment': 'Spotifyトークントラン',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('access_token', 'refresh_token'), name='unique_t_spotify_token_access_token_refresh_token_active')],
            },
        ),
    ]
