# Generated by Django 6.0.3 on 2026-04-09 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_t_spotifytoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_spotifyusertoken',
            options={'verbose_name': 'SpotifyUserトークントラン', 'verbose_name_plural': 'SpotifyUserトークントラン'},
        ),
        migrations.AlterModelTableComment(
            name='t_spotifyusertoken',
            table_comment='SpotifyUserトークントラン',
        ),
        migrations.RemoveConstraint(
            model_name='t_spotifyusertoken',
            name='unique_t_spotify_token_access_token_refresh_token_active',
        ),
        migrations.AddField(
            model_name='t_spotifyusertoken',
            name='email',
            field=models.EmailField(db_column='email', db_comment='メールアドレス', default=1, max_length=254, verbose_name='メールアドレス'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='t_spotifyusertoken',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='unique_t_spotify_user_token_access_token_refresh_token_active'),
        ),
        migrations.AlterModelTable(
            name='t_spotifyusertoken',
            table='t_spotify_user_token',
        ),
    ]
