# Generated by Django 6.0.3 on 2026-04-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalt_profile',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='historicalt_profile',
            name='icon',
            field=models.ForeignKey(blank=True, db_column='icon_id', db_comment='アイコン', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.t_fileresource', verbose_name='アイコン'),
        ),
        migrations.AddField(
            model_name='t_profile',
            name='icon',
            field=models.ForeignKey(blank=True, db_column='icon_id', db_comment='アイコン', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_t_profile_set', to='common.t_fileresource', verbose_name='アイコン'),
        ),
    ]
