# Generated by Django 6.0.3 on 2026-04-09 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_remove_historicalt_profile_icon_url_and_more'),
        ('artist', '0001_initial'),
        ('common', '0003_alter_t_spotifyusertoken_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Playlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', db_comment='タイトル', max_length=255, verbose_name='タイトル')),
                ('spotify_id', models.CharField(blank=True, db_column='spotify_id', db_comment='Spotify/ID', max_length=255, null=True, verbose_name='Spotify/ID')),
                ('artists', models.ManyToManyField(db_comment='アーティスト', related_name='artists_t_playlist_set', to='artist.t_artist', verbose_name='アーティスト')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('image', models.ForeignKey(blank=True, db_column='image_id', db_comment='画像', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_t_playlist_set', to='common.t_fileresource', verbose_name='画像')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='ユーザ', on_delete=django.db.models.deletion.CASCADE, related_name='user_t_playlist_set', to='account.t_profile', verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'プレイリストトラン',
                'verbose_name_plural': 'プレイリストトラン',
                'db_table': 't_playlist',
                'db_table_comment': 'プレイリストトラン',
            },
        ),
        migrations.CreateModel(
            name='T_PlaylistTrack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_comment='トラック名', max_length=255, verbose_name='トラック名')),
                ('preview_url', models.URLField(blank=True, db_column='preview_url', db_comment='プレビューURL', null=True, verbose_name='プレビューURL')),
                ('spotify_id', models.CharField(blank=True, db_column='spotify_id', db_comment='Spotify/ID', max_length=255, null=True, verbose_name='Spotify/ID')),
                ('artist', models.ForeignKey(blank=True, db_column='artist_id', db_comment='アーティスト', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_track_t_playlist_track_set', to='artist.t_artist', verbose_name='アーティスト')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('playlist', models.ForeignKey(db_column='playlist_id', db_comment='プレイリスト', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_t_playlist_track_set', to='playlist.t_playlist', verbose_name='プレイリスト')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プレイリストトラックトラン',
                'verbose_name_plural': 'プレイリストトラックトラン',
                'db_table': 't_playlist_track',
                'db_table_comment': 'プレイリストトラックトラン',
            },
        ),
        migrations.AddConstraint(
            model_name='t_playlist',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'spotify_id'), name='unique_t_playlist_user_spotify_id_active'),
        ),
        migrations.AddConstraint(
            model_name='t_playlisttrack',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('playlist', 'spotify_id'), name='unique_t_playlist_track_playlist_spotify_id_active'),
        ),
    ]
