# Generated by Django 6.0.3 on 2026-04-14 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='R_PlaylistArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('artist', models.ForeignKey(db_column='artist_id', db_comment='アーティスト', on_delete=django.db.models.deletion.CASCADE, related_name='artist_r_playlist_artist_set', to='artist.t_artist', verbose_name='アーティスト')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プレイリストアーティストリレーション',
                'verbose_name_plural': 'プレイリストアーティストリレーション',
                'db_table': 'r_playlist_artist',
                'db_table_comment': 'プレイリストアーティストリレーション',
            },
        ),
        migrations.CreateModel(
            name='T_Playlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', db_comment='タイトル', max_length=255, verbose_name='タイトル')),
                ('artists', models.ManyToManyField(db_comment='アーティスト', related_name='artists_t_playlist_set', through='playlist.R_PlaylistArtist', to='artist.t_artist', verbose_name='アーティスト')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('image', models.ForeignKey(blank=True, db_column='image_id', db_comment='画像', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_t_playlist_set', to='common.t_fileresource', verbose_name='画像')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='ユーザ', on_delete=django.db.models.deletion.CASCADE, related_name='user_t_playlist_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'プレイリストトラン',
                'verbose_name_plural': 'プレイリストトラン',
                'db_table': 't_playlist',
                'db_table_comment': 'プレイリストトラン',
            },
        ),
        migrations.AddField(
            model_name='r_playlistartist',
            name='playlist',
            field=models.ForeignKey(db_column='playlist_id', db_comment='プレイリスト', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_r_playlist_artist_set', to='playlist.t_playlist', verbose_name='プレイリスト'),
        ),
        migrations.CreateModel(
            name='T_PlaylistTrack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_comment='トラック名', max_length=255, verbose_name='トラック名')),
                ('spotify_id', models.CharField(db_column='spotify_id', db_comment='Spotify/ID', max_length=255, verbose_name='Spotify/ID')),
                ('artist_name', models.CharField(db_column='artist_name', db_comment='アーティスト名', max_length=255, verbose_name='アーティスト名')),
                ('artist_spotify_id', models.CharField(db_column='artist_spotify_id', db_comment='アーティストSpotify/ID', max_length=255, verbose_name='アーティストSpotify/ID')),
                ('artist_genres', models.JSONField(blank=True, db_column='artist_genres', db_comment='アーティストジャンル', default=list, verbose_name='アーティストジャンル')),
                ('artist_spotify_image', models.ForeignKey(blank=True, db_column='artist_spotify_image_id', db_comment='アーティストSpotify画像', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_spotify_image_t_artist_set', to='common.t_fileresource', verbose_name='アーティストSpotify画像')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('playlist', models.ForeignKey(db_column='playlist_id', db_comment='プレイリスト', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_t_playlist_track_set', to='playlist.t_playlist', verbose_name='プレイリスト')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プレイリストトラックトラン',
                'verbose_name_plural': 'プレイリストトラックトラン',
                'db_table': 't_playlist_track',
                'db_table_comment': 'プレイリストトラックトラン',
            },
        ),
        migrations.AddConstraint(
            model_name='r_playlistartist',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('playlist', 'artist'), name='unique_r_playlist_artist_playlist_artist_active'),
        ),
        migrations.AddConstraint(
            model_name='t_playlisttrack',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('playlist', 'spotify_id'), name='unique_t_playlist_track_playlist_spotify_id_active'),
        ),
    ]
