# Generated by Django 6.0.3 on 2026-04-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_playlisttrack',
            name='preview_url',
        ),
    ]
