# Generated by Django 6.0.3 on 2026-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_playlisttrack',
            name='album_id',
            field=models.CharField(blank=True, db_column='album_id', db_comment='アルバムID', max_length=255, null=True, verbose_name='アルバムID'),
        ),
        migrations.AddField(
            model_name='t_playlisttrack',
            name='album_name',
            field=models.CharField(blank=True, db_column='album_name', db_comment='アルバム名', max_length=255, null=True, verbose_name='アルバム名'),
        ),
        migrations.AddField(
            model_name='t_playlisttrack',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, db_column='duration_ms', db_comment='再生時間(ms)', null=True, verbose_name='再生時間(ms)'),
        ),
        migrations.AddField(
            model_name='t_playlisttrack',
            name='release_date',
            field=models.CharField(blank=True, db_column='release_date', db_comment='リリース日', max_length=20, null=True, verbose_name='リリース日'),
        ),
    ]
