# Generated by Django 6.0.3 on 2026-04-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_t_playlisttrack_album_id_t_playlisttrack_album_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_playlisttrack',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='t_playlisttrack',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='t_playlisttrack',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='t_playlisttrack',
            name='release_date',
        ),
        migrations.AddField(
            model_name='t_playlisttrack',
            name='spotify_album_id',
            field=models.CharField(blank=True, db_column='spotify_album_id', db_comment='SpotifyアルバムID', max_length=255, null=True, verbose_name='SpotifyアルバムID'),
        ),
        migrations.AddField(
            model_name='t_playlisttrack',
            name='spotify_album_name',
            field=models.CharField(blank=True, db_column='spotify_album_name', db_comment='Spotifyアルバム名', max_length=255, null=True, verbose_name='Spotifyアルバム名'),
        ),
        migrations.AddField(
            model_name='t_playlisttrack',
            name='spotify_duration_ms',
            field=models.PositiveIntegerField(blank=True, db_column='spotify_duration_ms', db_comment='Spotify再生時間(ms)', null=True, verbose_name='Spotify再生時間(ms)'),
        ),
        migrations.AddField(
            model_name='t_playlisttrack',
            name='spotify_release_date',
            field=models.CharField(blank=True, db_column='spotify_release_date', db_comment='Spotifyリリース日', max_length=20, null=True, verbose_name='Spotifyリリース日'),
        ),
    ]
