# Generated by Django 6.0.3 on 2026-04-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_remove_t_playlisttrack_album_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_playlisttrack',
            name='spotify_album_type',
            field=models.CharField(blank=True, choices=[('album', 'Album'), ('single', 'Single'), ('compilation', 'Compilation')], db_column='spotify_album_type', db_comment='Spotifyアルバム種別', null=True, verbose_name='Spotifyアルバム種別'),
        ),
    ]
