# Generated by Django 6.0.3 on 2026-04-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_t_playlisttrack_spotify_album_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_playlisttrack',
            name='display_artist_name',
            field=models.CharField(blank=True, db_column='display_artist_name', db_comment='アーティスト名/表示名', max_length=255, null=True, verbose_name='アーティスト名/表示名'),
        ),
    ]
