# Generated by Django 6.0.3 on 2026-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_t_playlisttrack_display_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_playlisttrack',
            name='spotify_artist_id',
            field=models.CharField(db_column='spotify_artist_id', db_comment='SpotifyアーティストID', default=1, max_length=255, verbose_name='SpotifyアーティストID'),
            preserve_default=False,
        ),
    ]
